name: ontolearn
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - matplotlib=3.3.4
  - pandas=1.2.3
  - pytorch=1.8.0
  - rdflib=6.0.2
  - scikit-learn=1.0.2
  - sortedcontainers=2.4.0
  - owlready2=0.40
  - flask=1.1.2
  - deap=1.3.1
  - httpx=0.21.1
  - parsimonious=0.8.1
  - tqdm=4.64.0
  # testing
  - tox=3.24.3
  - tox-conda=0.8.3
  - pytest=6.2.4
  - pytest-codeblocks=0.11.2
  # linting
  - flake8=3.9.2
  # docs
  - sphinx=4.0.2
  - sphinx_rtd_theme=0.5.1
  - myst-parser=0.15.2
  # # building
  - build=0.6.0
  # PIP
  - pip=21.0.1
  - pip:
    # testing
    - tox-run-before==0.1
    # docs
    - sphinxext-autox==0.0.2
    - sphinx-theme==1.0
    - sphinxcontrib-plantuml==0.21
    - plantuml-local-client==1.2021.10
