name: nces_env
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.5.7=py39h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - entrypoints=0.4=py39h06a4308_0
  - expat=2.3.0=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h7ca028e_0
  - glib=2.68.1=h36276a3_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.2.0=h06a4308_610
  - ipykernel=5.3.4=py39hb070fc8_0
  - ipython=7.22.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39h06a4308_1
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=5.3.0=py39h06a4308_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h14c3975_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=he1b5a44_3
  - matplotlib=3.3.4=py39h06a4308_0
  - matplotlib-base=3.3.4=py39h62a2d02_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py39h27cfd23_1
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.1=py39ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.1=py39h93e21f0_0
  - numpy-base=1.20.1=py39h7d8b39e_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1u=h7f8727e_0
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py39he98fc37_0
  - pip=21.0.1=py39h06a4308_0
  - platformdirs=2.5.2=py39h06a4308_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.7.1=py_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.4=hdb3f193_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=1_cp39
  - pytorch=1.8.1=py3.9_cuda10.2_cudnn7.6.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.24.1=py39ha9443f7_0
  - scipy=1.6.2=py39had2a1c9_1
  - setuptools=52.0.0=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.15.0=py_0
  - sqlite=3.35.4=hdfb4753_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.1=py39
  - torchvision=0.9.1=py39_cu102
  - tornado=6.1=py39h27cfd23_0
  - typing_extensions=4.6.3=py39h06a4308_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - aiofiles==23.1.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - altair==5.0.1
    - analytics-python==1.4.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - attrs==21.2.0
    - backoff==1.10.0
    - bcrypt==4.0.1
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - ccompiler==0.2.0
    - cffi==1.15.0
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cryptography==38.0.1
    - cython==0.29.32
    - datasets==2.2.2
    - deap==1.3.3
    - defusedxml==0.7.1
    - dill==0.3.4
    - docutils==0.18.1
    - et-xmlfile==1.1.0
    - fastapi==0.85.1
    - fastjsonschema==2.15.3
    - ffmpy==0.3.0
    - filelock==3.0.12
    - flask==2.2.2
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - gdown==3.13.0
    - gensim==4.1.2
    - gradio==3.38.0
    - gradio-client==0.2.10
    - h11==0.12.0
    - httpcore==0.13.7
    - httpx==1.0.0b0
    - huggingface-hub==0.16.4
    - idna==2.10
    - importlib-metadata==4.12.0
    - iniconfig==1.1.1
    - ipdb==0.13.9
    - ipywidgets==7.7.0
    - isodate==0.6.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.6.0
    - jupyter-client==7.3.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - kaggle==1.5.13
    - kivy-garden==0.1.4
    - linkify-it-py==1.0.3
    - markdown-it-py==2.1.0
    - markupsafe==2.1.1
    - mdit-py-plugins==0.3.1
    - mdurl==0.1.2
    - mistune==0.8.4
    - monotonic==1.6
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - nbclient==0.6.4
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.11
    - openpyxl==3.0.10
    - orjson==3.8.0
    - owlready2==0.41
    - packaging==20.9
    - pandas==2.0.0
    - pandocfilters==1.5.0
    - paramiko==2.11.0
    - parsimonious==0.10.0
    - pluggy==0.13.1
    - prometheus-client==0.14.1
    - protobuf==4.22.1
    - py==1.10.0
    - pyarrow==8.0.0
    - pycparser==2.21
    - pycryptodome==3.15.0
    - pydantic==1.10.2
    - pydub==0.25.1
    - pynacl==1.5.0
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - pytest==6.2.4
    - python-multipart==0.0.5
    - python-slugify==5.0.2
    - pyyaml==6.0
    - pyzmq==23.1.0
    - rdflib==6.2.0
    - regex==2022.6.2
    - requests==2.25.1
    - responses==0.18.0
    - rfc3986==1.5.0
    - seaborn==0.12.0
    - semantic-version==2.10.0
    - send2trash==1.8.0
    - sentencepiece==0.1.96
    - smart-open==5.2.1
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - starlette==0.20.4
    - tensorboard-logger==0.1.0
    - terminado==0.15.0
    - text-unidecode==1.3
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - toml==0.10.2
    - toolz==0.12.0
    - tqdm==4.64.0
    - traitlets==5.2.2.post1
    - transformers==4.19.2
    - typing-extensions==4.4.0
    - tzdata==2023.3
    - uc-micro-py==1.0.1
    - urllib3==1.26.6
    - uvicorn==0.18.3
    - webencodings==0.5.1
    - websockets==11.0.3
    - werkzeug==2.2.2
    - widgetsnbextension==3.6.0
    - xxhash==3.0.0
    - yarl==1.7.2
    - zipp==3.8.1
prefix: /home/user/.conda/envs/nces_env
